export const ADD = 'Add'
export const INCREMENT = 'INCREMENT'
export const GET_BANNER = 'GET_BANNER'
export const GET_PERSONALIZED = 'GET_PERSONALIZED'
export const GET_PLAYLIST_DETAIL = 'GET_PLAYLIST_DETAIL'
export const GET_SONG_URL = 'GET_SONG_URL'
