export { default as Index } from './index/index.js'
export { default as NewSong } from './newSong'
export { default as Detail } from './detail'
export { default as Playlist } from './playlist'
export { default as Search } from './search'
